project:
  type: book
  output-dir: _book

book:
  title: "DeepLearning x 101"
  author: "Jay & Luis"
  date: "2024. 4."
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: "Perceptron"
      chapters:
      - perceptron-intro.qmd
      - perceptron-lab_classification.qmd

    - part: "ANN"
      chapters:
      - ANN-intro.qmd
      - ANN-activation.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    mermaid:
      theme: default
    html-math-method: katex
    code-annotations: hover
    fig-cap-location: bottom
    tbl-cap-location: bottom



