project:
  type: book
  output-dir: _book

book:
  title: "DeepLearning x 101"
  author: "Jay & Luis & Soo"
  date: "2024. 4."
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: "Perceptron"
      chapters:
      - perceptron-intro.qmd
      - perceptron-lab_classification.qmd

    - part: "ANN"
      chapters:
      - ANN-intro.qmd
      - ANN-activation.qmd
      - ANN-forward.qmd
      - ANN-learning.qmd
      - ANN-lab_MNIST.qmd
      - ANN-backward.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    mermaid: 
      theme: neutral
    theme: cosmo  
    html-math-method: katex
    fig-cap-location: bottom
    tbl-cap-location: bottom
    reference-location: margin
    citation-location: margin
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.css" integrity="sha384-wcIxkf4k558AjM3Yz3BBFQUbk/zgIYC2R0QpeeYb+TwlBVMrlgLqwRjRtGZiK7ww" crossorigin="anonymous">
          <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.js" integrity="sha384-hIoBPJpTUs74ddyc4bFZSM1TVlQDA60VBbJS0oA934VSz82sBx1X7kSx2ATBDIyd" crossorigin="anonymous"></script>
          <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/contrib/auto-render.min.js" integrity="sha384-43gviWU0YVjaDtb/GhzOouOXtZMP/7XUzwPTstBeZFe/+rCMvRwr4yROQP43s0Xk" crossorigin="anonymous"onload="renderMathInElement(document.body);"></script>