project:
  type: website
  output-dir: docs

book:
  title: "DeepLearning x 101"
  author: "papa & flower fig"
  date: "2024. 4. 24."
  chapters:
    - index.qmd
    - intro.qmd
    - perceptron.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



