project:
  type: book
  output-dir: _book

book:
  title: "DeepLearning x 101"
  author: "Jay & Luis & Soo"
  date: "2024. 4."
  sidebar:
    background: light
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: "Perceptron"
      chapters:
      - perceptron-intro.qmd
      - perceptron-lab_classification.qmd

    - part: "ANN"
      chapters:
      - ANN-intro.qmd
      - ANN-activation.qmd
      - ANN-forward.qmd
      - ANN-learning.qmd
      - ANN-lab_MNIST.qmd
      - ANN-backward.qmd
      - ANN-lab_Backpro.qmd

    - part: "Related technologies"
      chapters:
      - TECH-initializing.qmd
      - TECH-optimizer.qmd

    - part: "CNN"
      chapters:
      - CNN-intro.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
    mermaid: 
      theme: neutral
    theme: lumen  
    html-math-method: katex
    fig-cap-location: bottom
    tbl-cap-location: bottom
    reference-location: margin
    citation-location: margin