project:
  type: book
  output-dir: _book

book:
  title: "DeepLearning x 101"
  author: "papa & flower fig"
  date: "2024. 4."
  chapters:
    - index.qmd
    - intro.qmd
    - perceptron.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    mermaid:
      theme: default



