# Preface {.unnumbered}

## Welcome

최근 전세계적으로 AI에 대한 관심이 증가하고 있습니다. 특히 **OPEN AI**의 **Chat-GPT**를 시작으로 다양한 생성형 AI가 발표되고 있습니다다.

이러한 AI 발전의 기초가되는 기술은 Machinelearning과 Deeplearning이 있습니다. 이중 가장 기초가 되는 Deeplearning을 활용하여 Data에서 사람이 찾을 수 없는 Features와 Patterns을 기계를 활용하여 찾기 위한 기술을 학습하고자 합니다.

이 사이트는 앞서 말한바와 같이 날로 중요해지는 **Deeplearning**에 대한 기초적인 이해부터 구현까지 학습하는 과정에 대한 기록물입니다. 나아가 **Deeplearning**기술을 활용하여 금융분야에 활용할 수 있는 방법을 연구하거나, 현재 다양한 금융공학의 기술과 접목시키고자 합니다.

또한, **Deeplearning**과 관련된 사항들 수식과 이론에 기반하여 기초적인 사항들을 가급적 빠짐없이 다룰 예정입니다. 또한, **Deeplearning**과 관련된 내용을 'engineering'관점에서 실제 기능을 구현하기 위한 코드를 포함할 예정이며, 이러한 소스 코드를 통해 이해의 폭을 높이고자 합니다. 물론 모든 코드와 그에 따른 결과는 매 페이지에서 확인할 수 있습니다.

::: {.callout-note}
본 사이트는 **[Quarto](https://quarto.org/)**를 기반으로 작성되었으며 실습환경에 관하여는 @tbl-packages 을 참고하기 바랍니다.
본 사이트 구축에 관한 소스 코드는 **[GitHub](https://jay-lee-85.github.io/DeepLearning/)**에서 확인할 수 있습니다.
:::

## Disclaimer

이 사이트는 모두에게 무료이며, "[Deep Learning from Scratch](https://github.com/ahn-github/saito-goki)"를 기반으로 학습자들이 연구한 내용을 담고 있습니다. 모든 내용에 대하여 출처를 밝힐 예정이나, 간혹 출처가 빠져 있는 경우 지속적으로 업데이트 하여, 원작자들의 권리를 침해하지 않고 오류를 수정해 나갈 것입니다.