# Overfitting
---

딥러닝 등 기계학습에서는 **오버피팅**을 항상조심해야 합니다. 훈련 또는 학습에 사용한 데이터에 지나치게 적응되어 다른 문제를 해결할 수 없는 상황을 회피하기 위해서죠.

## Understanding overfitting

오버피팅의 문제를 해결하기 위해서는 어떠한 상황에서 오버피팅이 발생하는지에 대한 이해가 필요합니다.

-   매개변수가 많고 표현력이 높은 모델
-   훈련 데이터가 적은 경우

위의 상황을 살펴보기 위해 7층의 신경망을 사용하여 네트워크의 복잡성을 지나치게 높이고, 60,000개인 MNIST 데이터셋의 훈련데이터 중 아주 적은 300개만 사용한다면 오버피팅이 발생할까요?

MNIST 데이터를 이용하여 훈련데이터와 검증데이터의 정확도를 아래 구현된 코드를 활용하여 비교해보도록 하겠습니다.

``` {python}
# coding: utf-8
import os
import sys

sys.path.append(os.pardir)  # 부모 디렉터리의 파일을 가져올 수 있도록 설정
import numpy as np
import matplotlib.pyplot as plt
from dataset.mnist import load_mnist
from common.multi_layer_net import MultiLayerNet
from common.optimizer import SGD

(x_train, t_train), (x_test, t_test) = load_mnist(normalize=True)

# 오버피팅을 재현하기 위해 학습 데이터 수를 줄임
x_train = x_train[:300]
t_train = t_train[:300]

# weight decay（가중치 감쇠） 설정 =======================
weight_decay_lambda = 0 # weight decay를 사용하지 않을 경우
# weight_decay_lambda = 0.1
# ====================================================

network = MultiLayerNet(input_size=784, hidden_size_list=[100, 100, 100, 100, 100, 100], output_size=10,
                        weight_decay_lambda=weight_decay_lambda)
optimizer = SGD(lr=0.01) # 학습률이 0.01인 SGD로 매개변수 갱신

max_epochs = 201
train_size = x_train.shape[0]
batch_size = 100

train_loss_list = []
train_acc_list = []
test_acc_list = []

iter_per_epoch = max(train_size / batch_size, 1)
epoch_cnt = 0

for i in range(1000000000):
    batch_mask = np.random.choice(train_size, batch_size)
    x_batch = x_train[batch_mask]
    t_batch = t_train[batch_mask]

    grads = network.gradient(x_batch, t_batch)
    optimizer.update(network.params, grads)

    if i % iter_per_epoch == 0:
        train_acc = network.accuracy(x_train, t_train)
        test_acc = network.accuracy(x_test, t_test)
        train_acc_list.append(train_acc)
        test_acc_list.append(test_acc)

        print("epoch:" + str(epoch_cnt) + ", train acc:" + str(train_acc) + ", test acc:" + str(test_acc))

        epoch_cnt += 1
        if epoch_cnt >= max_epochs:
            break


# 그래프 그리기==========
markers = {'train': 'o', 'test': 's'}
x = np.arange(max_epochs)
plt.plot(x, train_acc_list, marker='o', label='train', markevery=10)
plt.plot(x, test_acc_list, marker='s', label='test', markevery=10)
plt.xlabel("epochs")
plt.ylabel("accuracy")
plt.ylim(0, 1.0)
plt.legend(loc='lower right')
plt.show()
```

훈련 데이터를 사용한 정확도는 epoch가 100을 지날 무렴 정확도는 100%에 근접함에 반하여 검증 데이터를 사용한 정확도는 60%~70% 수준에 머무르는 것을 확인할 수 있습니다.

이는 결국 훈련 데이터에만 지나치게 적용(fitting)하여 검증 데이터 등에 대한 범용성을 확보하지 못하였음을 즉, 오버피팅이 발생하였음을 보여줍니다.

## Weight decay

첫번째로 살펴볼 오버피팅을 억제하는 수단으로는 **가중치 감소**(weight decay, $\lambda$)가 있습니다. 이는 학습과정 에서 가장 큰 가중치에 대해서는 그에 상응하는 큰 패널티를 부과하는 방법입니다.^[$L(\textbf{w})+\frac{1}{2}\lambda\textbf{W}^2$]


페널티는 어떻게 산출해야 할까요? 순전파시에 손실함수 값에 $\frac{1}{2}\lambda\textbf{W}^2$를 더하여 역전파시 가중치 업데이트 과정에서 그 마분값인 $\lambda\textbf{W}$를 더하게 되어 가중치가 큰 곳에 더 큰 패널티가 산출됩니다.

정규화의 강도를 조절, 즉, 강중치 감소 정도는 하이퍼파라미터인 $\lambda$로 조절합니다.

$$
\begin{align}
\textbf{L}^* &= \textbf{L}(\textbf{W})+\frac{1}{2}\lambda\textbf{W}^2 \\ \\
\textbf{W} &= \textbf{W} - \eta\frac{\partial{\textbf{L}^*}}{\partial{\textbf{W}}} \\
&= \textbf{W} - \eta\frac{\partial{(\textbf{L}+\frac{1}{2}\lambda\textbf{W}^2)}}{\partial{\textbf{W}}} \\
&= \textbf{W} - \eta(\frac{\partial{\textbf{L}}}{\partial{\textbf{W}}}+\frac{\partial\frac{1}{2}\lambda\textbf{W}^2}{\partial{\textbf{W}}}) \\
&= \textbf{W} - \eta(\frac{\partial{\textbf{L}}}{\partial{\textbf{W}}}+\lambda\textbf{W})
\end{align}
$$

::: {.callout-note}
## L2 Norm을 손실함수 값에 더한다? 그런데 왜 $\sqrt{w_1^2+w_2^2+\cdots+w_i^2}$이지?

-   L2 Norm은 $\sqrt{w_1^2+w_2^2+\cdots+w_i^2}$ 꼴로 나타나느데 왜 딥러닝의 가중치감소에서는 손실함수에 더하는 L2 Norm을 $\frac{1}{2}\lambda\textbf{W}^2$으로 정의되었을까요?
-   먼저 $\frac{1}{2}$항을 살펴보면 이는 수학적 편의를 위한 트릭에 해당합니다. 더해진 값을 역전파시 미분해야 하는데 $\lambda|\textbf{W}|_2^2$을 미분하는 것보다 $\frac{1}{2}\lambda|\textbf{W}|_2^2$을 미분하여  $\lambda\textbf{W}$가 되면 보다 식을 단순하게 만들 수 있기 때문입니다.
-   L2 Norm의 제곱은 어디로 갔을까요? 이는 최적화 과정에서 모델 가중치  $\textbf{W}$를 업데이트할때 제곱근 연산이 필요없기 때문에 불필요한 내용을 생락한 것입니다.
:::

지금까지 살펴 본 내용을 바탕으로 가중치 감소에 따른 효과를 살펴 보도록 하겠습니다. 하이퍼파라미터인 $\lambda$는 0.1로 설정하여 가중치 감소를 적용하였습니다.

``` {python}
#| echo: False
# coding: utf-8
import os
import sys

sys.path.append(os.pardir)  # 부모 디렉터리의 파일을 가져올 수 있도록 설정
import numpy as np
import matplotlib.pyplot as plt
from dataset.mnist import load_mnist
from common.multi_layer_net import MultiLayerNet
from common.optimizer import SGD

(x_train, t_train), (x_test, t_test) = load_mnist(normalize=True)

# 오버피팅을 재현하기 위해 학습 데이터 수를 줄임
x_train = x_train[:300]
t_train = t_train[:300]

# weight decay（가중치 감쇠） 설정 =======================
# weight_decay_lambda = 0 # weight decay를 사용하지 않을 경우
weight_decay_lambda = 0.1
# ====================================================

network = MultiLayerNet(input_size=784, hidden_size_list=[100, 100, 100, 100, 100, 100], output_size=10,
                        weight_decay_lambda=weight_decay_lambda)
optimizer = SGD(lr=0.01) # 학습률이 0.01인 SGD로 매개변수 갱신

max_epochs = 201
train_size = x_train.shape[0]
batch_size = 100

train_loss_list = []
train_acc_list = []
test_acc_list = []

iter_per_epoch = max(train_size / batch_size, 1)
epoch_cnt = 0

for i in range(1000000000):
    batch_mask = np.random.choice(train_size, batch_size)
    x_batch = x_train[batch_mask]
    t_batch = t_train[batch_mask]

    grads = network.gradient(x_batch, t_batch)
    optimizer.update(network.params, grads)

    if i % iter_per_epoch == 0:
        train_acc = network.accuracy(x_train, t_train)
        test_acc = network.accuracy(x_test, t_test)
        train_acc_list.append(train_acc)
        test_acc_list.append(test_acc)

        print("epoch:" + str(epoch_cnt) + ", train acc:" + str(train_acc) + ", test acc:" + str(test_acc))

        epoch_cnt += 1
        if epoch_cnt >= max_epochs:
            break


# 그래프 그리기==========
markers = {'train': 'o', 'test': 's'}
x = np.arange(max_epochs)
plt.plot(x, train_acc_list, marker='o', label='train', markevery=10)
plt.plot(x, test_acc_list, marker='s', label='test', markevery=10)
plt.xlabel("epochs")
plt.ylabel("accuracy")
plt.ylim(0, 1.0)
plt.legend(loc='lower right')
plt.show()
```

여전히 오버피팅이 발생하고 있지만 이전과 비교하여 상당부분 훈련 데이터와 검증 데이터간 정확도의 차이가 줄어든 것을 확인할 수 있습니다. 즉, 오버피팅이 억제된 효과를 확인할 수 있습니다.

## Drop out

